### PR TITLE
fix: load plugin/ in autocmds before 'loadplugins'

### LINKED ISSUE #33: plugin/* not loaded when `nvim {file}`
- `nvim --version`: 0.10
- `git --version`: 2.24.3
- Operating system/version: macOS Catalina 10.15.7 19H2026 x86_64
- Terminal name/version: alacritty

### Steps to reproduce
- `$ mkdir plugin1/plugin -p`
- `$ echo 'echomsg "helloworld"' > plugin1/plugin/x.vim`
- `$ mv plugin1 pckr/opt/ # move to where pckr opt dir (local plugin seems not work)`
- add plugin spec:
```lua
    {
      'xxx/plugin1',
      cond = event('FileType'),
    };
```
- `$ touch a.go`
- `$ nvim a.go`
- `:mes`

### Actual behaviour
no message

### Expected behaviour
one messsage:
`helloworld`

### pckr files

<details>
<summary>Plugin specification file(s)</summary>

```lua
    {
      'xxx/plugin1',
      cond = event('FileType'),
    };
```

</details>

### PR DESCRIPTION
**Pull request by lewis6991**

### CODE REVIEW

**Comment by zeertzjq** [comment]
This change breaks plugins that are configured via global variables. Now pckr.nvim must be loaded after the global variables are set.

**Comment by lewis6991** [comment]
Sorry I don't understand. I load pckr before `plugin/` is loaded. The variable is just used to signal when `plugin/*` is sourced during initialisation instead of using `VimEnter` which happens later.

**Comment by zeertzjq** [comment]
Sorry, it seems that the breakage I observed came from something else.

**Comment by lewis6991** [comment]
Ok. Do you have any more details?

**Comment by zeertzjq** [comment]
Hmm, it seems that the behavior of pckr.nvim hasn't changed, but I somehow just noticed that pckr.nvim loads `plugin/` from the packages immediately after `require('pckr').add()`.

**Comment by lewis6991** [comment]
Only if run pckr after initialisation, otherwise when else would you load `plugin/`? I've tried to make sure to follow the semantics of `:packadd` as close as possible.

**Comment by zeertzjq** [comment]
Hmm, it seems to do that in `init.lua` as well. With the following `init.lua`:
```lua
local function bootstrap_pckr()
  local pckr_path = vim.fn.stdpath("data") .. "/pckr/pckr.nvim"

  if not (vim.uv or vim.loop).fs_stat(pckr_path) then
    vim.fn.system({
      'git',
      'clone',
      "--filter=blob:none",
      'https://github.com/lewis6991/pckr.nvim',
      pckr_path
    })
  end

  vim.opt.rtp:prepend(pckr_path)
end

bootstrap_pckr()

print(vim.g.undotree_DiffCommand)
require('pckr').add{
  { 'mbbill/undotree', start = true },
}
print(vim.g.undotree_DiffCommand)
```
It prints:
```
nil
diff
```
which means calling `require('pckr').add()` loads the `plugin/` directories.

**Comment by lewis6991** [comment]
Looks like a bug with `start = true`.

**Comment by lewis6991** [comment]
This behaviour is caused by `do_loadplugins()` in `pckr/loader.lua`. You can disable this by setting `_native_loadplugins = true`.

I implemented a custom `loadplugins` behaviour because the built-in implementation was slow. However I think I might have resolved this in https://github.com/neovim/neovim/pull/24191

Need to re-assess if it is still necessary. #49

**Pull request merged**
